AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyLambdaFunctionV1:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "lambda_function.lambda_handler"
      Role: "arn:aws:iam::{ACCOUNT_ID}:role/{lambda_role}"
      Code:
        S3Bucket: "{S3Bucket}"
        S3Key: "SampleLambda.zip"
        # S3ObjectVersion: "{S3ObjectVersion}"
      Runtime: "python3.6"
      Timeout: 3
